import "~/styles/globals.css";

import { type Metadata } from "next";
import { headers } from "next/headers";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const hdrs = headers();

  return (
    <html lang="pt-BR" className={geist.variable} suppressHydrationWarning>
      <body>
        {/* Passa os headers da request para o tRPC (cookies/sessão) */}
        <TRPCReactProvider headers={hdrs}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
